<a href="https://colab.research.google.com/github/INHARYU/aipython/blob/main/20240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#시험 리뷰

1. 영어점수와 수학점수가 합해서 100점이 넘으면 pass, 한 과목 점수가 40점 미만이라면 과목 미달로 fail이다.
a = list(map(int,input(.split())))
2가지 하넙ㄴ에 받기.


In [ ]:
a = list(map(int,input().split()))

if sum(a) > 100:
  if a[0] > 40 and a[1] > 40:
    print('PASS')
  elif a[0] < 40 :
    print('ENG FAIL')
  else:
    print('MATH FAIL')
else:
  print('FAIL')

35 35
FAIL


2. N개의 숫자가 공백없이 입력된다. 이 숫자를 모두 합쳐서 합을 출력하는 프로그램을 작성하시오.

In [ ]:
Num = input()
Num_List= list(Num)
aa = map(int,Num_List)
print(sum(aa))

123123
12


3. 다음 리스트에서 확장자가 PNG나 JPG인 파일명.확장자를 출력하는 파이썬 코드를 작성하세요

In [6]:
n=int(input())
a=[input() for _ in range(n)]
b=[i for i in a if i.split('.')[-1]== 'jpg' or i.split('.')[-1] == 'png']
print(b)

KeyboardInterrupt: Interrupted by user

넘파이
패키지, 모듈

패키지: 모듈을 포함하는 디렉토리이다. 파이썬을 프로글매을 구성하는 여러 모듈을 그룹화하여 관리. 모듈의 집합.
pip는 파이썬 패키지 관리 명령어.

pip install numpy

pip는 기본 파이썬을 사용할 떄를 의미한다.

사용하는 개발 환경에 따라 명령어가 약간씩 달라진다.

패키지와 모듈의 관계
모듈은 낱개의 파이썬 파일. 모듈은 재사용의 의미를 갖고 있다. import문을 사용해서 불러 온다.
import pandas as pd
import numpy as np

넘파이 사용 이유:  큰 배열과 행렬 연산에 필요한 다양한 함수를 제공

특정모듈만 불러올때는 from module



In [7]:
import numpy as np
print(np.__version__)

1.25.2


스칼라는 차원이 없다.
넘파이 5가지 속성. 데이터 분석할 때 데이터 구조를 알아야 한다. 데이터의 크기 등을 아는데 사용한다.
shape, 구성반환
size, 전채갯수
ndim, 차원갯수
nbyte, 바이트 수
dtype, 데이터 타입

int와 uint는 다른데, 데이터 범주마다 표현 범위가 달라진다.

In [10]:
# 1차원 배열
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

#배열의 형태, 차원, 데이터 타입 확인
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Data Type:", arr2d.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [11]:
#하나는 리스트 하나는 넘파이의 객체가 된다. 두개의 타입이 다르다.
lst =[1,2,3]
arr = np.array(lst)
print(type(lst), lst)
print(type(arr), arr)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'> [1 2 3]


In [12]:
# 0부터 9까지
arr = np.arange(10)
print(arr)
# 2부터 19까지, 간격은 2
arr = np.arange(2, 20, 2)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [13]:
# 1차원 배열
zeros_1d = np.zeros(5)
print(zeros_1d)
# 2차원 배열 3행 4열
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# 1차원 배열
ones_1d = np.ones(5)
print(ones_1d)
# 2차원 배열
ones_2d = np.ones((3, 4))
print(ones_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# 1차원 배열
arr_1d = np.random.rand(5)
print(arr_1d)
# 2차원 배열
arr_2d = np.random.rand([[2, 3]])
print(arr_2d)

[0.60236808 0.49959928 0.28879253 0.99648527 0.44397668]


TypeError: 'list' object cannot be interpreted as an integer

In [15]:
# 0부터 1까지 5개의 값
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [22]:
arr=np.array([[1,2,3],[4,5,6]])
print("합:",np.sum(arr))
print("행의 원소 합: ",np.sum(arr, axis=0))
print("열의 원소 합: ",np.sum(arr, axis=1))
print("평균:",np.mean(arr))
print("행의 원소 평균: ",np.mean(arr, axis=0))
print("열의 원소 평균: ",np.mean(arr, axis=1))
print("최대:",np.max(arr))
print("최소:",np.min(arr))
print("행의 원소 최대값: ",np.max(arr, axis=0))
print("행의 원소 최소값: ",np.min(arr, axis=0))
print("열의 원소 최대값: ",np.max(arr, axis=1))
print("열의 원소 최소값: ",np.min(arr, axis=1))
print(np.argmax(arr))
print(np.argmin(arr))
print("분산:",np.var(arr))
print("표준편차:",np.std(arr))

합: 21
행의 원소 합:  [5 7 9]
열의 원소 합:  [ 6 15]
평균: 3.5
행의 원소 평균:  [2.5 3.5 4.5]
열의 원소 평균:  [2. 5.]
최대: 6
최소: 1
행의 원소 최대값:  [4 5 6]
행의 원소 최소값:  [1 2 3]
열의 원소 최대값:  [3 6]
열의 원소 최소값:  [1 4]
5
0
분산: 2.9166666666666665
표준편차: 1.707825127659933


In [24]:
#1
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [25]:
#2
ones_2d = np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#3
arr = np.linspace(0,1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [28]:
arr1 = np.ones([3,4])
print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [30]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [59]:
A = np.array(
 [[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]
 )
print(A.shape)
print(A[3,3]) # 행은 3 열은3
print(A[0:2,:2])
print(A[3:,3:])
print(A[0,0:2])
print(A[4,3:5])

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[1 2]
[24 25]


In [60]:
arr=np.array([[1,2,3],[4,5,6]])
arr_T=arr.transpose() # 2행 3열 --> 3행 2열
arr_F=arr.flatten() # 2차원인것을 --> 1차원으로 만듦.
arr_R=arr_F.reshape(3,2) # 다시 1차원을 3행 2열로
print(arr)
print(arr_T)
print(arr_F)
print(arr_R)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [77]:
a= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32],[33,34,35,36]]])
print(a.shape)
a_3d=a.reshape(3,4,3)
print(a_3d)
arr_F=a.flatten()
print(arr_F)

(3, 3, 4)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [78]:
arr1 = np.arange(1,5)
arr2 = np.ones(4)
print(arr1 , arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 > arr2)


[1 2 3 4] [1. 1. 1. 1.]
[2. 3. 4. 5.]
[0. 1. 2. 3.]
[False  True  True  True]


In [79]:
arr1 = np.random.randint(11, size=4)
print(arr1)
print(arr1 + 2)
print(arr1 * 2)

[8 1 8 3]
[10  3 10  5]
[16  2 16  6]
